# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 719113ef42356f80653737c9b9056da5bd7e0c8589149789fd00271da69ea25647450d30f263bb3830f5b20b447d60f06e80061b2ff97281567be0011d65d65c

test:
  secret_key_base: a50e449e8b8b65714d5c5ff730af2e0d112e204c3d4b61e483a913958bb5546183c85d761e58eaa0020591d63de3713e2e2d51bcbb006eef25bf890c1b271830

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
